### PR TITLE
Don't full text search attachments.

### PR DESCRIPTION
**Pull request by vlymar**
The current search strategy does not handle large attachments well.
When an attachment is uploaded, we attempt to extract the text and store
it in the attachments table. That text is then used for full text search
when filtering in /opportunities. This triggers very expensive joins,
aggregations, and to_tsvector function calls which collectively consume
massive amounts of memory.

Re-enabling search of attachment text will require optimization, such as
creating a dedicated pg search index.

### CODE REVIEW

**Comment by jrubenoff** [comment]
Could we instead disable full-text search for attachments over a certain file size?

**Comment by jrubenoff** [comment]
(^^ To clarify, I'm wondering whether that might be very easy to implement. If not, let's just merge this.)

**Comment by vlymar** [comment]
We'd run the risk of bumping into the same issue if many small attachments were uploaded, as problem comes from overall table size not the size of any one attachment. Picking a threshold would also be difficult.

**Comment by jrubenoff** [comment]
Alrighty, this LGTM then!

**Comment by vlymar** [comment]
Decided not to merge this PR, and opened https://github.com/dobtco/dispatch/issues/93

**Pull request closed without merging**
